export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const EVENT_ROUTE = '/'
export const WATCHLIST_ROUTE = '/watchlist'
export const EVENTPOST_ROUTE = '/event'
